# --- Special Colors ---
background            #000000
foreground            #c4c8d4

# White Cursor
cursor                #ffffff
cursor_text_color     #000000

# Selection
selection_foreground  #000000
selection_background  #ff6575

# --- Tab Bar Colors ---
active_tab_foreground   #000000
active_tab_background   #ff6575
inactive_tab_foreground #80879d
inactive_tab_background #121214

# --- 16 ANSI Color Palette ---

# Black / Grey
color0  #16161a
color8  #52586b

# Red / Coral Accent
color1  #ff6575
color9  #ff7b89

# Green
color2  #4fd6be
color10 #72f8dd

# Yellow
color3  #e3d182
color11 #f3e293

# Blue (Mapped to Light Red)
color4  #ff7b89
color12 #ff94a0

# Magenta
color5  #d183ff
color13 #e2a3ff

# Cyan (Mapped to Light Red)
color6  #ff7b89
color14 #ff94a0

# White
color7  #c4c8d4
color15 #ffffff
